export default [
  "Cardiovascular Diseases",
  "Respiratory Diseases",
  "Endocrine Disorders",
  "Neurological Disorders",
  "Gastrointestinal Diseases",
  "Musculoskeletal Disorders",
  "Autoimmune Diseases",
  "Infectious Diseases",
  "Mental Health Disorders",
  "Dermatological Conditions",
  "Hematological Disorders",
  "Kidney Diseases",
  "Liver Diseases",
  "Cancers",
  "Genetic Disorders",
  "Metabolic Disorders",
  "Pregnancy-Related Conditions",
  "Eye Disorders",
  "Ear Disorders",
  "Oral Health Issues",
  "Sleep Disorders",
  "Allergic Conditions",
  "Urinary Tract Disorders",
  "Sexual Health Issues",
  "Immunological Disorders",
  "Acute Conditions",
  "Chronic Conditions",
  "Health Conditions Related to Aging",
  "Pediatric Conditions",
  "Preventive Health Issues",
  "Occupational Health Disorders",
  "Environmental Health Issues",
  "Cardiac Arrhythmias",
  "Pulmonary Disorders",
  "Thyroid Disorders",
  "Nutritional Deficiencies",
  "Chronic Pain Syndromes",
  "Hormonal Disorders",
  "Psychiatric Disorders",
  "Substance Use Disorders",
  "Behavioral Health Issues",
  "Reproductive Health Issues",
  "Injury and Trauma",
  "Post-Surgical Complications",
  "Health Issues Related to Obesity",
  "Vascular Disorders",
  "End-of-Life Conditions",
  "Rare Diseases",
  "Chronic Fatigue Syndromes",
  "Coagulation Disorders",
];
